# Generated by Django 4.0 on 2021-12-14 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('qty_buy', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'group of loyalty',
                'verbose_name_plural': 'groups of loyalty',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +999999999 Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')], verbose_name='phone number')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='city')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='balance')),
                ('loyal_group', models.CharField(default='None', max_length=50, verbose_name='group of loyalty')),
                ('qty_buy', models.PositiveIntegerField(default=0, verbose_name='quantity buying')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
            },
        ),
    ]
